version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: lab3
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_ROOT_PASSWORD=pass123456
          - MYSQL_DATABASE=mysql
          - MYSQL_USER=app
          - MYSQL_PASSWORD=vulnerables
        volumes:
          - .:/application
        ports:
          - "8082:3306"
  website:
    container_name: dvwa
    build:
      context: ./
    ports:
      - 9000:80
