apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dvwa
spec:
  selector:
    matchLabels:
      app: dvwa-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dvwa-app
    spec:
      containers:
      - image: localhost:32000/vulnerables/web-dvwa:k8s
        name: dvwa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: dvwa
