apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
spec:
  selector:
    matchLabels:
      app: dvwa-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dvwa-app
    spec:
      containers:
      - image: localhost:32000/sql:k8s
        name: sql
        imagePullPolicy: IfNotPresent
	env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass123456
        - name: MYSQL_DATABASE
          value: dvwa
        - name: MYSQL_USER
          value: app
        - name: MYSQL_PASSWORD
          value: vulnerables
	args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 80
          name: sql
